### ISSUE TITLE
Cant get it to work.

### ISSUE THREAD

**Issue by El-9o** [impresspages-plugins/Favicon#2]
Hello.

Im trying to change the favicon on my IP-site.
Ive changed all the favicon.ico's in the whole directory.
And I have placed your plugin in the /Plugin folder
I have changed favicon.ico in /assets/img folder
I have activated plugin.
I also changed name of your plugin-folder from Favicon-master to Favicon, so it will fit how its written in Plugin/Favicon/Filter.php:
_ if (is_object($response) && method_exists($response, 'setFavicon')) {
            $response->setFavicon(ipFileUrl('Plugin/Favicon/assets/favicon.ico'));_

Still, the favicon doesnt change.

Could you help me out?

Im using a theme, altitude.

Thanks.

**Comment by maskas** [comment]
Browsers cache favicon very heavily. Even if you clear the cache, some browsers still keep the old favicon. I would suggest you to try another browser which haven't been used to open that website.

**Comment by El-9o** [comment]
Thanks for your help. That worked!

But now the favicon is "blurry", not showing clearly as it should. Do have any idea why that would be the case?

Thanks.

**Comment by maskas** [comment]
It is not related to ImpressPages. But basically, you have to create a real ico file with an image editor that supports that. ico file supports multiple sizes in one file: 8x8 16x16 32x32. Browser will automatically use the best one.

**Comment by El-9o** [comment]
Okay. Thanks so much for you help. Have a nice day.
